[project]
name = "nurion"
version = "0.1.0"
description = "Nurion data platform workspace"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "control",
    "engine",
]

[dependency-groups]
dev = [
    "pandas>=2.3.3",
]

[tool.ruff]
extend-exclude = ["**/anvil_pb2.py", "**/anvil_pb2_grpc.py"]

[tool.ruff.lint.per-file-ignores]
"**/anvil_pb2.py" = ["E501"]
"**/anvil_pb2_grpc.py" = ["E501"]
