apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: data-ray-cluster-enwei
  namespace: data-processing-development
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: 0.0.0.0
      num-cpus: "0"
      object-store-memory: "50000000000"
      plasma-directory: /dev/shm
      temp-dir: /ray/tmp
    serviceType: NodePort
    template:
      metadata:
        annotations:
          karpenter.sh/do-not-disrupt: "true"
      spec:
        containers:
        - args:
          - pip install pylance
          env:
          - name: CLUSTERINFO_THIS_CLUSTER
            value: oracle-osaka
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: aws-secrets
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: aws-secrets
          - name: RAY_TMPDIR
            value: /ray/tmp
          - name: RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION
            value: "0.75"
          envFrom:
          - configMapRef:
              name: ray-cluster-config
          image: ocir.us-ashburn-1.oci.oraclecloud.com/axsgshhbf0lb/lax:gpu-amd-2bbe85bb
          imagePullPolicy: Always
          name: ray-head
          resources:
            limits:
              cpu: "16"
              memory: 150Gi
            requests:
              cpu: "16"
              memory: 150Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /ray/tmp
            name: ray-tmp
          - mountPath: /root/.config/rclone
            name: rclone-vol
          - mountPath: /mnt/nvme0
            name: nvme0
          - mountPath: /mnt/nvme1
            name: nvme1
          - mountPath: /mnt/nvme2
            name: nvme2
          - mountPath: /mnt/nvme3
            name: nvme3
          - mountPath: /mnt/nvme4
            name: nvme4
          - mountPath: /mnt/nvme5
            name: nvme5
          - mountPath: /mnt/nvme6
            name: nvme6
          - mountPath: /mnt/nvme7
            name: nvme7
        imagePullSecrets:
        - name: ocirsecret
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: lax
        - effect: NoSchedule
          key: amd.com/gpu
          operator: Exists
        volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 60Gi
          name: dshm
        - emptyDir:
            sizeLimit: 400Gi
          name: ray-tmp
        - name: rclone-vol
          secret:
            secretName: rclone-conf
        - hostPath:
            path: /mnt/nvme0
          name: nvme0
        - hostPath:
            path: /mnt/nvme1
          name: nvme1
        - hostPath:
            path: /mnt/nvme2
          name: nvme2
        - hostPath:
            path: /mnt/nvme3
          name: nvme3
        - hostPath:
            path: /mnt/nvme4
          name: nvme4
        - hostPath:
            path: /mnt/nvme5
          name: nvme5
        - hostPath:
            path: /mnt/nvme6
          name: nvme6
        - hostPath:
            path: /mnt/nvme7
          name: nvme7
  rayVersion: 2.50.0
  workerGroupSpecs:
  - groupName: ray-workers
    maxReplicas: 5
    minReplicas: 0
    numOfHosts: 1
    rayStartParams:
      object-store-memory: "1000000000000"
      plasma-directory: /dev/shm
      temp-dir: /ray/tmp
    replicas: 5
    scaleStrategy: {}
    template:
      metadata: {}
      spec:
        containers:
        - args:
          - pip install pylance
          env:
          - name: CLUSTERINFO_THIS_CLUSTER
            value: oracle-osaka
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: aws-secrets
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: aws-secrets
          - name: RAY_TMPDIR
            value: /ray/tmp
          envFrom:
          - configMapRef:
              name: ray-cluster-config
          image: ocir.us-ashburn-1.oci.oraclecloud.com/axsgshhbf0lb/lax:gpu-amd-2bbe85bb
          imagePullPolicy: Always
          name: ray-worker
          resources:
            limits:
              amd.com/gpu: "8"
              cpu: "96"
              memory: 1760Gi
            requests:
              amd.com/gpu: "8"
              cpu: "96"
              memory: 1760Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /ray/tmp
            name: ray-tmp
          - mountPath: /root/.config/rclone
            name: rclone-vol
          - mountPath: /mnt/nvme0
            name: nvme0
          - mountPath: /mnt/nvme1
            name: nvme1
          - mountPath: /mnt/nvme2
            name: nvme2
          - mountPath: /mnt/nvme3
            name: nvme3
          - mountPath: /mnt/nvme4
            name: nvme4
          - mountPath: /mnt/nvme5
            name: nvme5
          - mountPath: /mnt/nvme6
            name: nvme6
          - mountPath: /mnt/nvme7
            name: nvme7
        imagePullSecrets:
        - name: ocirsecret
        initContainers:
        - command:
          - sh
          - -c
          - |
            echo "Waiting for lock..."
            flock /mnt/nvme0/.model-sync.lock -c '
              for MODEL_NAME in s3://ai-lumalabs-checkpoints-ap-se-2/william/hf/Qwen3-VL-235B-A22B-Instruct s3://ai-lumalabs-checkpoints-ap-se-2/william/hf/Qwen3-32B s3://ai-lumalabs-checkpoints-ap-se-2/william/hf/Qwen3-8B ba://ai-lumalabs-checkpoints/shared/Qwen3-VL-32B-Instruct s3://ai-lumalabs-checkpoints-ap-se-2/william/hf/Qwen3-Omni-30B-A3B-Instruct s3://ai-lumalabs-checkpoints-ap-se-2/william/hf/Qwen3-Omni-30B-A3B-Captioner; do
                export MODEL_NAME_=${MODEL_NAME//[\/:]/_}
                if [ ! -f /mnt/nvme0/vllm/ckpts/${MODEL_NAME_}/.model_fetched ]; then
                  echo "Running rclone to copy from model-cache-seeder via HTTP..."
                  mkdir -p /mnt/nvme0/vllm/ckpts/${MODEL_NAME_}
                  rclone sync -P :http:/vllm/ckpts/${MODEL_NAME_} /mnt/nvme0/vllm/ckpts/${MODEL_NAME_} \
                    --http-url http://model-cache-seeder.default.svc.cluster.local:8000 \
                    --transfers 16 --retries 10 --timeout 60m --contimeout 10m
                  touch /mnt/nvme0/vllm/ckpts/${MODEL_NAME_}/.model_fetched
                else
                  echo "${MODEL_NAME_} already fetched on this node."
                fi
              done
            '
          image: rclone/rclone
          imagePullPolicy: IfNotPresent
          name: model-cache-fetch
          resources: {}
          volumeMounts:
          - mountPath: /mnt/nvme0
            name: nvme0
          - mountPath: /root/.config/rclone
            name: rclone-vol
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: lax
        - effect: NoSchedule
          key: amd.com/gpu
          operator: Exists
        volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1000Gi
          name: dshm
        - emptyDir:
            sizeLimit: 400Gi
          name: ray-tmp
        - name: rclone-vol
          secret:
            secretName: rclone-conf
        - hostPath:
            path: /mnt/nvme0
          name: nvme0
        - hostPath:
            path: /mnt/nvme1
          name: nvme1
        - hostPath:
            path: /mnt/nvme2
          name: nvme2
        - hostPath:
            path: /mnt/nvme3
          name: nvme3
        - hostPath:
            path: /mnt/nvme4
          name: nvme4
        - hostPath:
            path: /mnt/nvme5
          name: nvme5
        - hostPath:
            path: /mnt/nvme6
          name: nvme6
        - hostPath:
            path: /mnt/nvme7
          name: nvme7
