# Copyright 2025 nurion team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""WorkQueue gRPC Client - Python client for WorkQueue server."""

from __future__ import annotations

import logging
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional

import grpc

logger = logging.getLogger(__name__)

# Proto imports will be generated by grpc_tools.protoc
# For now, we define stub classes that will be replaced
try:
    from . import workqueue_pb2 as pb2
    from . import workqueue_pb2_grpc as pb2_grpc
except ImportError:
    pb2 = None  # type: ignore
    pb2_grpc = None  # type: ignore
    logger.warning(
        "gRPC stubs not found. Run: "
        "python -m grpc_tools.protoc -I proto --python_out=python/workqueue_py "
        "--grpc_python_out=python/workqueue_py proto/workqueue.proto"
    )


@dataclass
class Message:
    """A message claimed from the queue."""

    msg_id: str
    queue: str
    payload: bytes
    created_at: float
    metadata: Dict[str, str] = field(default_factory=dict)
    claim_token: Optional[str] = None

    @classmethod
    def from_proto(cls, proto: Any) -> "Message":
        """Create Message from protobuf."""
        return cls(
            msg_id=proto.msg_id,
            queue=proto.queue,
            payload=proto.payload,
            created_at=proto.created_at,
            metadata=dict(proto.metadata),
        )


class WorkQueueClient:
    """Python client for WorkQueue server.

    This client provides a simple interface to interact with the WorkQueue
    gRPC server. It handles heartbeat management automatically.

    Example:
        client = WorkQueueClient("localhost:50051", worker_id="worker-0")
        client.start()

        # Push messages
        msg_id = client.push("my-queue", b"hello world")

        # Claim and process messages
        messages = client.claim("my-queue", batch_size=10)
        for msg in messages:
            # Process message
            process(msg.payload)

        # Acknowledge processed messages
        client.ack("my-queue", [m.msg_id for m in messages])

        client.stop()
    """

    def __init__(
        self,
        server_address: str,
        worker_id: str,
        heartbeat_interval_secs: float = 5.0,
        connect_timeout_secs: float = 10.0,
    ):
        """Initialize the client.

        Args:
            server_address: Server address in "host:port" format
            worker_id: Unique identifier for this worker
            heartbeat_interval_secs: Interval between heartbeat pings
            connect_timeout_secs: Timeout for initial connection
        """
        self.server_address = server_address
        self.worker_id = worker_id
        self.heartbeat_interval = heartbeat_interval_secs
        self.connect_timeout = connect_timeout_secs

        self._channel: Optional[grpc.Channel] = None
        self._stub: Optional[Any] = None
        self._lease_id: str = ""

        # Heartbeat management
        self._heartbeat_thread: Optional[threading.Thread] = None
        self._heartbeat_running = False
        self._heartbeat_lock = threading.Lock()

    def start(self) -> None:
        """Connect to server and start heartbeat.

        Raises:
            RuntimeError: If connection or lease acquisition fails
        """
        if pb2 is None or pb2_grpc is None:
            raise RuntimeError(
                "gRPC stubs not generated. Run: "
                "python -m grpc_tools.protoc -I proto --python_out=python/workqueue_py "
                "--grpc_python_out=python/workqueue_py proto/workqueue.proto"
            )

        self._channel = grpc.insecure_channel(self.server_address)
        self._stub = pb2_grpc.WorkQueueStub(self._channel)

        # Start heartbeat stream
        self._heartbeat_running = True
        self._heartbeat_thread = threading.Thread(
            target=self._heartbeat_loop,
            daemon=True,
            name=f"heartbeat-{self.worker_id}",
        )
        self._heartbeat_thread.start()

        # Wait for initial lease
        deadline = time.time() + self.connect_timeout
        while time.time() < deadline:
            if self._lease_id:
                logger.info(
                    f"Connected to {self.server_address}, lease_id={self._lease_id}"
                )
                return
            time.sleep(0.1)

        # Clean up resources before raising exception
        self.stop()
        raise RuntimeError(
            f"Failed to acquire lease from server within {self.connect_timeout}s"
        )

    def stop(self) -> None:
        """Stop heartbeat and close connection."""
        self._heartbeat_running = False

        if self._heartbeat_thread:
            self._heartbeat_thread.join(timeout=2.0)
            self._heartbeat_thread = None

        if self._channel:
            self._channel.close()
            self._channel = None

        self._stub = None
        self._lease_id = ""
        logger.info(f"Disconnected from {self.server_address}")

    def _heartbeat_loop(self) -> None:
        """Background thread for heartbeat streaming."""
        reconnect_attempts = 0

        def ping_generator() -> Iterator[Any]:
            while self._heartbeat_running:
                yield pb2.HeartbeatPing(
                    worker_id=self.worker_id,
                    lease_id=self._lease_id,
                    timestamp=int(time.time() * 1000),
                )
                time.sleep(self.heartbeat_interval)

        while self._heartbeat_running:
            try:
                responses = self._stub.HeartbeatStream(ping_generator())
                for pong in responses:
                    if not self._heartbeat_running:
                        break
                    with self._heartbeat_lock:
                        self._lease_id = pong.lease_id
                        reconnect_attempts = 0  # Reset on successful connection
                        if not pong.ok:
                            logger.warning("Lease invalidated by server")
                            self._lease_id = ""
            except grpc.RpcError as e:
                if self._heartbeat_running:
                    reconnect_attempts += 1
                    # Only log first attempt as warning, rest as debug to reduce noise
                    if reconnect_attempts == 1:
                        logger.warning(f"Heartbeat disconnected, reconnecting...")
                    elif reconnect_attempts % 10 == 0:
                        logger.debug(f"Heartbeat reconnect attempt {reconnect_attempts}")
                    time.sleep(1.0)

    @property
    def lease_id(self) -> str:
        """Get current lease ID."""
        with self._heartbeat_lock:
            return self._lease_id

    def _check_connected(self) -> None:
        """Verify client is connected."""
        if not self._stub:
            raise RuntimeError("Client not started. Call start() first.")

    # =========================================================================
    # Consumer API
    # =========================================================================

    def claim(
        self,
        queue: str,
        batch_size: int = 1,
        timeout_ms: int = 5000,
    ) -> List[Message]:
        """Claim messages from a queue.

        Args:
            queue: Queue name to claim from
            batch_size: Maximum number of messages to claim
            timeout_ms: Wait timeout in milliseconds (0 = no wait)

        Returns:
            List of claimed messages (may be empty if queue is empty)

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.ClaimRequest(
            queue=queue,
            worker_id=self.worker_id,
            lease_id=self.lease_id,
            batch_size=batch_size,
            timeout_ms=timeout_ms,
        )

        response = self._stub.Claim(request)
        messages = [Message.from_proto(m) for m in response.messages]
        if messages:
            if len(response.claim_tokens) != len(messages):
                raise RuntimeError(
                    "Claim response missing claim_tokens or length mismatch "
                    f"(messages={len(messages)}, claim_tokens={len(response.claim_tokens)})"
                )
            for msg, token in zip(messages, response.claim_tokens):
                msg.claim_token = token
        return messages

    def ack(
        self,
        queue: str,
        msg_ids: List[str],
        claim_tokens: Optional[List[str]] = None,
        state_namespace: Optional[str] = None,
        state_puts: Optional[Dict[str, bytes]] = None,
        state_deletes: Optional[List[str]] = None,
    ) -> int:
        """Acknowledge messages as processed, optionally with atomic state updates.

        Args:
            queue: Queue name
            msg_ids: List of message IDs to acknowledge
            claim_tokens: List of claim tokens (1:1 with msg_ids)
            state_namespace: Optional namespace for state updates (e.g., "{job_id}/{stage_id}")
            state_puts: Optional dict of state key -> value to set
            state_deletes: Optional list of state keys to delete

        Returns:
            Number of messages successfully acknowledged

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        if msg_ids:
            if not claim_tokens or len(claim_tokens) != len(msg_ids):
                raise ValueError(
                    "claim_tokens is required and must match msg_ids length "
                    f"(msg_ids={len(msg_ids)}, claim_tokens={len(claim_tokens) if claim_tokens else 0})"
                )

        request = pb2.AckRequest(
            queue=queue,
            msg_ids=msg_ids,
            worker_id=self.worker_id,
            lease_id=self.lease_id,
            state_namespace=state_namespace or "",
            state_puts=state_puts or {},
            state_deletes=state_deletes or [],
            claim_tokens=claim_tokens or [],
        )

        response = self._stub.Ack(request)
        if response.failed_ids:
            logger.warning(f"Failed to ack message IDs: {response.failed_ids}")
        return response.acked_count

    def nack(
        self,
        queue: str,
        msg_ids: List[str],
        claim_tokens: Optional[List[str]] = None,
        reason: str = "processing_failed",
        delay_ms: int = 0,
        state_namespace: Optional[str] = None,
        state_puts: Optional[Dict[str, bytes]] = None,
        state_deletes: Optional[List[str]] = None,
    ) -> int:
        """Return messages to queue for retry.

        Args:
            queue: Queue name
            msg_ids: List of message IDs to return
            claim_tokens: List of claim tokens (1:1 with msg_ids)
            reason: Reason for nack ("processing_failed", "payload_missing", "skip")
            delay_ms: Delay before message can be reclaimed
            state_namespace: Optional namespace for atomic state updates
            state_puts: State keys to set atomically with nack
            state_deletes: State keys to delete atomically with nack

        Returns:
            Number of messages returned to queue

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        if msg_ids:
            if not claim_tokens or len(claim_tokens) != len(msg_ids):
                raise ValueError(
                    "claim_tokens is required and must match msg_ids length "
                    f"(msg_ids={len(msg_ids)}, claim_tokens={len(claim_tokens) if claim_tokens else 0})"
                )

        reason_enum = {
            "processing_failed": pb2.NACK_REASON_PROCESSING_FAILED,
            "payload_missing": pb2.NACK_REASON_PAYLOAD_MISSING,
            "skip": pb2.NACK_REASON_SKIP,
        }.get(reason, pb2.NACK_REASON_UNSPECIFIED)

        request = pb2.NackRequest(
            queue=queue,
            msg_ids=msg_ids,
            worker_id=self.worker_id,
            lease_id=self.lease_id,
            reason=reason_enum,
            delay_ms=delay_ms,
            claim_tokens=claim_tokens or [],
            state_namespace=state_namespace or "",
            state_puts=state_puts or {},
            state_deletes=state_deletes or [],
        )

        response = self._stub.Nack(request)
        return response.nacked_count

    def ack_and_forward(
        self,
        upstream_queue: str,
        upstream_msg_ids: List[str],
        upstream_claim_tokens: Optional[List[str]],
        downstream_queue: str,
        downstream_payloads: List[bytes],
        state_namespace: Optional[str] = None,
        state_puts: Optional[Dict[str, bytes]] = None,
        state_deletes: Optional[List[str]] = None,
    ) -> List[str]:
        """Atomically ack upstream messages, push to downstream, and update state.

        This is the key operation for exactly-once semantics between stages.

        Args:
            upstream_queue: Queue to ack from
            upstream_msg_ids: Message IDs to acknowledge
            upstream_claim_tokens: Claim tokens (1:1 with upstream_msg_ids)
            downstream_queue: Queue to push to
            downstream_payloads: Payloads for new downstream messages
            state_namespace: Optional namespace for state updates
            state_puts: Optional dict of state key -> value to set
            state_deletes: Optional list of state keys to delete

        Returns:
            List of new downstream message IDs

        Raises:
            RuntimeError: If the operation fails
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        if upstream_msg_ids:
            if (
                not upstream_claim_tokens
                or len(upstream_claim_tokens) != len(upstream_msg_ids)
            ):
                raise ValueError(
                    "upstream_claim_tokens is required and must match upstream_msg_ids length "
                    f"(upstream_msg_ids={len(upstream_msg_ids)}, "
                    f"upstream_claim_tokens={len(upstream_claim_tokens) if upstream_claim_tokens else 0})"
                )

        request = pb2.AckAndForwardRequest(
            upstream_queue=upstream_queue,
            upstream_msg_ids=upstream_msg_ids,
            downstream_queue=downstream_queue,
            downstream_payloads=downstream_payloads,
            worker_id=self.worker_id,
            lease_id=self.lease_id,
            state_namespace=state_namespace or "",
            state_puts=state_puts or {},
            state_deletes=state_deletes or [],
            upstream_claim_tokens=upstream_claim_tokens or [],
        )

        response = self._stub.AckAndForward(request)
        if not response.success:
            raise RuntimeError("AckAndForward failed")
        return list(response.new_msg_ids)

    # =========================================================================
    # State API
    # =========================================================================

    def state_get(
        self,
        namespace: str,
        keys: List[str],
    ) -> Dict[str, bytes]:
        """Get state values by keys.

        Args:
            namespace: State namespace (e.g., "{job_id}/{stage_id}")
            keys: List of keys to fetch

        Returns:
            Dict mapping key to value (missing keys not included)

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.StateGetRequest(
            namespace=namespace,
            keys=keys,
        )

        response = self._stub.StateGet(request)
        return dict(response.values)

    def state_put(
        self,
        namespace: str,
        puts: Optional[Dict[str, bytes]] = None,
        deletes: Optional[List[str]] = None,
    ) -> tuple[int, int]:
        """Put/delete state values.

        Args:
            namespace: State namespace (e.g., "{job_id}/{stage_id}")
            puts: Dict of key -> value to set
            deletes: List of keys to delete

        Returns:
            Tuple of (puts_count, deletes_count)

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.StatePutRequest(
            namespace=namespace,
            puts=puts or {},
            deletes=deletes or [],
        )

        response = self._stub.StatePut(request)
        return response.puts_count, response.deletes_count

    # =========================================================================
    # Producer API
    # =========================================================================

    def push(
        self,
        queue: str,
        payload: bytes,
        metadata: Optional[Dict[str, str]] = None,
    ) -> str:
        """Push a message to a queue.

        Args:
            queue: Queue name
            payload: Message payload
            metadata: Optional metadata

        Returns:
            The new message ID

        Raises:
            grpc.RpcError: If the request fails (e.g., queue is full)
        """
        self._check_connected()

        request = pb2.PushRequest(
            queue=queue,
            payload=payload,
            metadata=metadata or {},
        )

        response = self._stub.Push(request)
        return response.msg_id

    def push_batch(self, queue: str, payloads: List[bytes]) -> List[str]:
        """Push multiple messages to a queue.

        Args:
            queue: Queue name
            payloads: List of message payloads

        Returns:
            List of new message IDs

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.PushBatchRequest(
            queue=queue,
            payloads=payloads,
        )

        response = self._stub.PushBatch(request)
        return list(response.msg_ids)

    # =========================================================================
    # Admin API
    # =========================================================================

    def create_queue(self, queue: str, max_depth: int = 0) -> bool:
        """Create a queue.

        Args:
            queue: Queue name
            max_depth: Maximum queue depth (0 = unlimited)

        Returns:
            True if queue was created, False if it already existed
        """
        self._check_connected()

        request = pb2.CreateQueueRequest(
            queue=queue,
            max_depth=max_depth,
        )

        response = self._stub.CreateQueue(request)
        return response.created

    def delete_queue(self, queue: str, force: bool = False) -> tuple[bool, int]:
        """Delete a queue.

        Args:
            queue: Queue name
            force: Force delete non-empty queue

        Returns:
            Tuple of (deleted, messages_deleted)
        """
        self._check_connected()

        request = pb2.DeleteQueueRequest(
            queue=queue,
            force=force,
        )

        response = self._stub.DeleteQueue(request)
        return response.deleted, response.messages_deleted

    def get_stats(self, queue: Optional[str] = None) -> Dict[str, Any]:
        """Get queue statistics.

        Args:
            queue: Specific queue name, or None for all queues

        Returns:
            Dictionary with queue statistics
        """
        self._check_connected()

        request = pb2.GetStatsRequest(queue=queue or "")
        response = self._stub.GetStats(request)

        return {
            "queues": {
                q: {
                    "pending_count": s.pending_count,
                    "claimed_count": s.claimed_count,
                    "total_pushed": s.total_pushed,
                    "total_acked": s.total_acked,
                }
                for q, s in response.queues.items()
            },
            "total_workers": response.total_workers,
            "uptime_secs": response.uptime_secs,
        }

    # =========================================================================
    # Queue Completion API
    # =========================================================================

    def mark_queue_finished(self, queue: str) -> bool:
        """Mark a queue as finished (no more messages will be pushed).

        This should be called by the upstream stage master after all messages
        have been pushed to the queue.

        Args:
            queue: Queue name to mark as finished

        Returns:
            True if successfully marked

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.MarkQueueFinishedRequest(queue=queue)
        response = self._stub.MarkQueueFinished(request)
        return response.success

    def is_queue_finished(self, queue: str) -> Dict[str, Any]:
        """Check if queue is finished and safe to exit.

        This provides an authoritative check for worker exit conditions,
        avoiding race conditions from stale statistics.

        Args:
            queue: Queue name to check

        Returns:
            Dictionary with:
                - finished: True if queue marked as finished by upstream
                - drained: True if pending==0 && claimed==0
                - safe_to_exit: True if finished && drained (worker can exit)
                - pending_count: Current pending message count
                - claimed_count: Current claimed message count

        Raises:
            grpc.RpcError: If the request fails
        """
        self._check_connected()

        request = pb2.IsQueueFinishedRequest(queue=queue)
        response = self._stub.IsQueueFinished(request)
        return {
            "finished": response.finished,
            "drained": response.drained,
            "safe_to_exit": response.safe_to_exit,
            "pending_count": response.pending_count,
            "claimed_count": response.claimed_count,
        }

    def __enter__(self) -> "WorkQueueClient":
        """Context manager entry."""
        self.start()
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit."""
        self.stop()
