# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import workqueue_pb2 as workqueue__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workqueue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkQueueStub(object):
    """============================================================================
    WorkQueue Service Definition
    ============================================================================

    === Consumer API ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Claim = channel.unary_unary(
                '/workqueue.WorkQueue/Claim',
                request_serializer=workqueue__pb2.ClaimRequest.SerializeToString,
                response_deserializer=workqueue__pb2.ClaimResponse.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/workqueue.WorkQueue/Ack',
                request_serializer=workqueue__pb2.AckRequest.SerializeToString,
                response_deserializer=workqueue__pb2.AckResponse.FromString,
                _registered_method=True)
        self.Nack = channel.unary_unary(
                '/workqueue.WorkQueue/Nack',
                request_serializer=workqueue__pb2.NackRequest.SerializeToString,
                response_deserializer=workqueue__pb2.NackResponse.FromString,
                _registered_method=True)
        self.AckAndForward = channel.unary_unary(
                '/workqueue.WorkQueue/AckAndForward',
                request_serializer=workqueue__pb2.AckAndForwardRequest.SerializeToString,
                response_deserializer=workqueue__pb2.AckAndForwardResponse.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/workqueue.WorkQueue/Push',
                request_serializer=workqueue__pb2.PushRequest.SerializeToString,
                response_deserializer=workqueue__pb2.PushResponse.FromString,
                _registered_method=True)
        self.PushBatch = channel.unary_unary(
                '/workqueue.WorkQueue/PushBatch',
                request_serializer=workqueue__pb2.PushBatchRequest.SerializeToString,
                response_deserializer=workqueue__pb2.PushBatchResponse.FromString,
                _registered_method=True)
        self.StateGet = channel.unary_unary(
                '/workqueue.WorkQueue/StateGet',
                request_serializer=workqueue__pb2.StateGetRequest.SerializeToString,
                response_deserializer=workqueue__pb2.StateGetResponse.FromString,
                _registered_method=True)
        self.StatePut = channel.unary_unary(
                '/workqueue.WorkQueue/StatePut',
                request_serializer=workqueue__pb2.StatePutRequest.SerializeToString,
                response_deserializer=workqueue__pb2.StatePutResponse.FromString,
                _registered_method=True)
        self.HeartbeatStream = channel.stream_stream(
                '/workqueue.WorkQueue/HeartbeatStream',
                request_serializer=workqueue__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=workqueue__pb2.HeartbeatPong.FromString,
                _registered_method=True)
        self.CreateQueue = channel.unary_unary(
                '/workqueue.WorkQueue/CreateQueue',
                request_serializer=workqueue__pb2.CreateQueueRequest.SerializeToString,
                response_deserializer=workqueue__pb2.CreateQueueResponse.FromString,
                _registered_method=True)
        self.DeleteQueue = channel.unary_unary(
                '/workqueue.WorkQueue/DeleteQueue',
                request_serializer=workqueue__pb2.DeleteQueueRequest.SerializeToString,
                response_deserializer=workqueue__pb2.DeleteQueueResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/workqueue.WorkQueue/GetStats',
                request_serializer=workqueue__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=workqueue__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class WorkQueueServicer(object):
    """============================================================================
    WorkQueue Service Definition
    ============================================================================

    === Consumer API ===
    """

    def Claim(self, request, context):
        """Claim messages from a queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Acknowledge messages as processed (delete them)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Nack(self, request, context):
        """Negative acknowledge - return messages to queue for retry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckAndForward(self, request, context):
        """Atomic operation: Ack upstream + Push downstream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """=== Producer API ===

        Push a single message to queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushBatch(self, request, context):
        """Push multiple messages to queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StateGet(self, request, context):
        """=== State API (integrated operator state) ===

        Get state values by keys
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatePut(self, request, context):
        """Put/delete state values
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatStream(self, request_iterator, context):
        """=== Heartbeat (bidirectional streaming) ===

        Worker heartbeat to maintain lease
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQueue(self, request, context):
        """=== Admin API ===

        Create a queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQueue(self, request, context):
        """Delete a queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get queue statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkQueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=workqueue__pb2.ClaimRequest.FromString,
                    response_serializer=workqueue__pb2.ClaimResponse.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=workqueue__pb2.AckRequest.FromString,
                    response_serializer=workqueue__pb2.AckResponse.SerializeToString,
            ),
            'Nack': grpc.unary_unary_rpc_method_handler(
                    servicer.Nack,
                    request_deserializer=workqueue__pb2.NackRequest.FromString,
                    response_serializer=workqueue__pb2.NackResponse.SerializeToString,
            ),
            'AckAndForward': grpc.unary_unary_rpc_method_handler(
                    servicer.AckAndForward,
                    request_deserializer=workqueue__pb2.AckAndForwardRequest.FromString,
                    response_serializer=workqueue__pb2.AckAndForwardResponse.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=workqueue__pb2.PushRequest.FromString,
                    response_serializer=workqueue__pb2.PushResponse.SerializeToString,
            ),
            'PushBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBatch,
                    request_deserializer=workqueue__pb2.PushBatchRequest.FromString,
                    response_serializer=workqueue__pb2.PushBatchResponse.SerializeToString,
            ),
            'StateGet': grpc.unary_unary_rpc_method_handler(
                    servicer.StateGet,
                    request_deserializer=workqueue__pb2.StateGetRequest.FromString,
                    response_serializer=workqueue__pb2.StateGetResponse.SerializeToString,
            ),
            'StatePut': grpc.unary_unary_rpc_method_handler(
                    servicer.StatePut,
                    request_deserializer=workqueue__pb2.StatePutRequest.FromString,
                    response_serializer=workqueue__pb2.StatePutResponse.SerializeToString,
            ),
            'HeartbeatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.HeartbeatStream,
                    request_deserializer=workqueue__pb2.HeartbeatPing.FromString,
                    response_serializer=workqueue__pb2.HeartbeatPong.SerializeToString,
            ),
            'CreateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQueue,
                    request_deserializer=workqueue__pb2.CreateQueueRequest.FromString,
                    response_serializer=workqueue__pb2.CreateQueueResponse.SerializeToString,
            ),
            'DeleteQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQueue,
                    request_deserializer=workqueue__pb2.DeleteQueueRequest.FromString,
                    response_serializer=workqueue__pb2.DeleteQueueResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=workqueue__pb2.GetStatsRequest.FromString,
                    response_serializer=workqueue__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workqueue.WorkQueue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workqueue.WorkQueue', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkQueue(object):
    """============================================================================
    WorkQueue Service Definition
    ============================================================================

    === Consumer API ===
    """

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/Claim',
            workqueue__pb2.ClaimRequest.SerializeToString,
            workqueue__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/Ack',
            workqueue__pb2.AckRequest.SerializeToString,
            workqueue__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Nack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/Nack',
            workqueue__pb2.NackRequest.SerializeToString,
            workqueue__pb2.NackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckAndForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/AckAndForward',
            workqueue__pb2.AckAndForwardRequest.SerializeToString,
            workqueue__pb2.AckAndForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/Push',
            workqueue__pb2.PushRequest.SerializeToString,
            workqueue__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/PushBatch',
            workqueue__pb2.PushBatchRequest.SerializeToString,
            workqueue__pb2.PushBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StateGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/StateGet',
            workqueue__pb2.StateGetRequest.SerializeToString,
            workqueue__pb2.StateGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatePut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/StatePut',
            workqueue__pb2.StatePutRequest.SerializeToString,
            workqueue__pb2.StatePutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/workqueue.WorkQueue/HeartbeatStream',
            workqueue__pb2.HeartbeatPing.SerializeToString,
            workqueue__pb2.HeartbeatPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/CreateQueue',
            workqueue__pb2.CreateQueueRequest.SerializeToString,
            workqueue__pb2.CreateQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/DeleteQueue',
            workqueue__pb2.DeleteQueueRequest.SerializeToString,
            workqueue__pb2.DeleteQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workqueue.WorkQueue/GetStats',
            workqueue__pb2.GetStatsRequest.SerializeToString,
            workqueue__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
